version: '2.1'

services:
  wifi-connect:
    container_name: wifi-connect
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    environment:
      PORTAL_SSID: 'WiFi'
      PORTAL_PASSPHRASE: 'MyWiFiP4ssw0rd'
      BALENA_ARCH: rpi
      BALENA_MACHINE_NAME: raspberry-pi

  node-red:
    container_name: node-red
    build: ./node-red/node-red
    volumes:
      - 'volume-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    expose:
      - "80"
    depends_on:
      - "google-iot"
    environment:
      USERNAME: 'NodeRedUser'
      PASSWORD: '$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN'
      PORT: 1241

  google-iot:
    container_name: google-iot
    build: ./google-iot
    volumes:
      - 'volume-data:/data/google-iot'
    restart: always
    privileged: true
    network_mode: host
    depends_on:
      - "wifi-connect"
    ports:
      - "8883:8883"
    environment:
      BALENA_MACHINE_NAME: 'raspberry-pi'
      GOOGLE_IOT_PROJECT: 'google-iot-project-id'
      GOOGLE_IOT_REGION: 'google-iot-project-region'
      GOOGLE_IOT_REGISTRY: 'google-iot-project-registry'
      GOOGLE_IOT_SERVICE_ACCOUNT_TOKEN: '--JSON TOKEN HERE--'

volumes:
  volume-data: